# Generated by Django 5.1.2 on 2024-12-16 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(blank=True, default=1, help_text='Укажите способ оплаты', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.payment_method', verbose_name='Способ оплаты'),
        ),
    ]
