# Generated by Django 5.1.2 on 2024-12-16 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(blank=True, help_text='Укажите способ оплаты', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.payment_method', verbose_name='Способ оплаты'),
        ),
    ]
