# Generated by Django 5.1.2 on 2024-10-19 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Введите название бренда', max_length=100, verbose_name='Название бренда')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Введите название категории', max_length=100, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(help_text='Введите название линейки', max_length=100, verbose_name='Название линейки')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taste', models.CharField(blank=True, help_text='Укажите вкус', max_length=100, null=True, verbose_name='Вкус')),
                ('description', models.TextField(help_text='Введите описание товара', verbose_name='Описание товара')),
                ('image', models.FileField(blank=True, help_text='Выберите изображение товара', null=True, upload_to='img/', verbose_name='Изображение товара')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Укажите цену товара', max_digits=8, verbose_name='Цена')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=0, default=0, help_text='Укажите количество товара', max_digits=8, verbose_name='Количество товара')),
                ('stronghold', models.CharField(help_text='Укажите Крепость', max_length=10, verbose_name='Крепость жидкости')),
                ('brand', models.ForeignKey(blank=True, help_text='Укажите бренд товара', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='goods.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(blank=True, help_text='Укажите категорию товара', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='goods.categories', verbose_name='Категория')),
                ('line', models.ForeignKey(blank=True, help_text='Укажите линейку товара', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='goods.line', verbose_name='Линейка')),
            ],
        ),
    ]
