# Generated by Django 5.1.2 on 2024-10-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=models.FileField(blank=True, help_text='Выберите изображение товара', null=True, upload_to='images/', verbose_name='Изображение товара'),
        ),
    ]
