# Generated by Django 5.1.2 on 2024-11-28 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_remove_goods_brand_goods_tegs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Введите название бренда', max_length=100, verbose_name='Название бренда')),
            ],
        ),
        migrations.AlterField(
            model_name='goods',
            name='description',
            field=models.TextField(help_text='Введите описание товара', null=True, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=models.FileField(help_text='Выберите изображение товара', null=True, upload_to='images/', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='taste',
            field=models.CharField(help_text='Укажите вкус или модель товара', max_length=100, null=True, verbose_name='Вкус/модель товара'),
        ),
        migrations.AddField(
            model_name='goods',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Укажите бренд товара', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='goods.brand', verbose_name='Бренд'),
        ),
    ]
