# Generated by Django 5.1.2 on 2024-11-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_brand_alter_goods_description_alter_goods_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='brand',
        ),
        migrations.AddField(
            model_name='line',
            name='brand',
            field=models.CharField(help_text='Введите название бренда', max_length=100, null=True, verbose_name='Название бренда'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
