# Generated by Django 5.1.2 on 2024-11-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_remove_goods_brand_line_brand_delete_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='brand',
            field=models.CharField(default='', help_text='Введите название бренда', max_length=100, null=True, verbose_name='Название бренда'),
        ),
        migrations.AlterField(
            model_name='line',
            name='line',
            field=models.CharField(default='', help_text='Введите название линейки', max_length=100, verbose_name='Название линейки'),
        ),
    ]
