# Generated by Django 5.1.2 on 2024-11-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_alter_line_brand_alter_line_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='line',
            field=models.CharField(blank=True, default='', help_text='Введите название линейки', max_length=100, verbose_name='Название линейки'),
        ),
    ]
